name: intl_phone_number_input
description: A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
version: 0.6.0
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

  libphonenumber: ^2.0.0
  libphonenumber_plugin: ^0.2.3
  equatable: ^2.0.2



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
  collection: ^1.15.0-nullsafety.4
flutter:
  assets:
    - assets/flags/
